Is19 denouncer credibility
CodeCollegeGroup/django-rest-denunciation pull request #34
Opened 2018-06-18 03:33 UTC by danielmarques28

2018-06-18 04:49 UTC, ViniciusBernardo requested changes
Considere dar merge com a branch master antes de abrir um novo pull request. Várias alterações presentes na master desapareceram neste PR.

2018-06-18 04:52 UTC, icaropires requested changes
Várias alterações importantes da master sumiram durante o merge. Além disso os algoritmos estão com muitos if's reduntantes e complexidade extra desnecessária. Código não está compátivel com funcionalidades que estão sendo desenvolvidas em paralelo em outras branchs.

2018-06-19 02:46 UTC, icaropires approved these changes

2018-06-19 02:46 UTC, ViniciusBernardo approved these changes

2018-06-19 02:54 UTC, merged